---
- hosts: web
  remote_user: root

  tasks:
  - name: Update repo
    git:
      repo: 'https://github.com/haukot/english_reader.git'
      dest: /srv/english_reader
      update: yes
  - name: Restart docker-compose
    docker_compose:
      project_src: /srv/english_reader
      files:
        - docker-compose.production.yml
      build: no
      restarted: yes